export const AI_CONSTANTS = {
  MODEL: "gpt-4o",
  CONTEXT_WINDOW: 128_000,
  MAX_OUTPUT_TOKENS: 16_384,
  TEMPERATURE: 0,
  DEFAULT_CONFIDENCE_THRESHOLD: 0.8,
  SYSTEM_PROMPT_VERSION: 1,
  MAX_RETRY_ATTEMPTS: 3
} as const; 